### ISSUE TITLE
Additional test failures with python 3.7

### ISSUE THREAD

**Issue by keszybz** [gristlabs/asttokens#18]
New stuff that wasn't listed in #16:
```
======================================================================
FAIL: test_adjacent_strings (tests.test_astroid.TestAstroid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/asttokens-1.1.10/tests/test_mark_tokens.py", line 183, in test_adjacent_strings
    node_name + ":'x y z'   # comment2\n       'a b c'   # comment3\n       'u v w'"
AssertionError: Items in the first set but not the second:
"Const:'x y z'"
Items in the second set but not the first:
"Const:'x y z'   # comment2\n       'a b c'   # comment3\n       'u v w'"

======================================================================
FAIL: test_token_methods (tests.test_asttokens.TestASTTokens)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/asttokens-1.1.10/tests/test_asttokens.py", line 46, in test_token_methods
    self.assertEqual(atok.prev_token(atok.tokens[5]), atok.tokens[3])
AssertionError: Token(type=56, string='\n', start=(2, 0), end=(2, 1)[40 chars]s=22) != Token(type=4, string='\n', start=(1, 20), end=(1, 21[61 chars]s=21)

======================================================================
FAIL: test_adjacent_strings (tests.test_mark_tokens.TestMarkTokens)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/asttokens-1.1.10/tests/test_mark_tokens.py", line 183, in test_adjacent_strings
    node_name + ":'x y z'   # comment2\n       'a b c'   # comment3\n       'u v w'"
AssertionError: Items in the first set but not the second:
"Str:'x y z'"
Items in the second set but not the first:
"Str:'x y z'   # comment2\n       'a b c'   # comment3\n       'u v w'"
```

This is with
python3-3.7.0-1.fc29.x86_64
python3-astroid-2.0.0-0.4dev3.fc29.noarch

**Comment by dsagal** [comment]
I believe these are fixed in v1.1.11. Please reopen if anything is still broken.
